// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: laptop/laptop_message.proto

package protoc

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Laptop struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // Unique identifier for the laptop
	Brand    string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`       // Brand of the laptop
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`         // Model name of the laptop
	Cpu      *CPU                   `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`           // CPU information
	Ram      *Memory                `protobuf:"bytes,5,opt,name=ram,proto3" json:"ram,omitempty"`           // Memory information
	Gpus     []*GPU                 `protobuf:"bytes,6,rep,name=gpus,proto3" json:"gpus,omitempty"`         // List of GPUs
	Storages []*Storage             `protobuf:"bytes,7,rep,name=storages,proto3" json:"storages,omitempty"` // List of storage devices
	Screen   *Screen                `protobuf:"bytes,8,opt,name=screen,proto3" json:"screen,omitempty"`     // Screen information
	Keyboard *Keyboard              `protobuf:"bytes,9,opt,name=keyboard,proto3" json:"keyboard,omitempty"` // Keyboard information
	// Types that are valid to be assigned to Weight:
	//
	//	*Laptop_WeightKg
	//	*Laptop_WeightLbs
	Weight        isLaptop_Weight        `protobuf_oneof:"weight"`
	PriceUsd      float64                `protobuf:"fixed64,12,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`         // Price of the laptop in USD
	ReleaseYear   uint32                 `protobuf:"varint,13,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"` // Release year of the laptop
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`        // Updation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Laptop) Reset() {
	*x = Laptop{}
	mi := &file_laptop_laptop_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Laptop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Laptop) ProtoMessage() {}

func (x *Laptop) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Laptop.ProtoReflect.Descriptor instead.
func (*Laptop) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_message_proto_rawDescGZIP(), []int{0}
}

func (x *Laptop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Laptop) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Laptop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Laptop) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Laptop) GetRam() *Memory {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *Laptop) GetGpus() []*GPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Laptop) GetStorages() []*Storage {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *Laptop) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Laptop) GetKeyboard() *Keyboard {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

func (x *Laptop) GetWeight() isLaptop_Weight {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Laptop) GetWeightKg() float64 {
	if x != nil {
		if x, ok := x.Weight.(*Laptop_WeightKg); ok {
			return x.WeightKg
		}
	}
	return 0
}

func (x *Laptop) GetWeightLbs() float64 {
	if x != nil {
		if x, ok := x.Weight.(*Laptop_WeightLbs); ok {
			return x.WeightLbs
		}
	}
	return 0
}

func (x *Laptop) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *Laptop) GetReleaseYear() uint32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Laptop) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isLaptop_Weight interface {
	isLaptop_Weight()
}

type Laptop_WeightKg struct {
	WeightKg float64 `protobuf:"fixed64,10,opt,name=weight_kg,json=weightKg,proto3,oneof"` // Weight in kilograms
}

type Laptop_WeightLbs struct {
	WeightLbs float64 `protobuf:"fixed64,11,opt,name=weight_lbs,json=weightLbs,proto3,oneof"` // Weight in pounds
}

func (*Laptop_WeightKg) isLaptop_Weight() {}

func (*Laptop_WeightLbs) isLaptop_Weight() {}

var File_laptop_laptop_message_proto protoreflect.FileDescriptor

const file_laptop_laptop_message_proto_rawDesc = "" +
	"\n" +
	"\x1blaptop/laptop_message.proto\x1a\x1blaptop/screen_message.proto\x1a\x1dlaptop/keyboard_message.proto\x1a\x1elaptop/processor_message.proto\x1a\x1blaptop/memory_message.proto\x1a\x1claptop/storage_message.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xb5\x04\n" +
	"\x06Laptop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x05brand\x18\x02 \x01(\tB*\xbaH'\xc8\x01\x01r\"\x10\x01\x182R\x04DellR\x02HPR\x06LenovoR\x04AsusR\x04AcerR\x05brand\x12 \n" +
	"\x04name\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18dR\x04name\x12\x16\n" +
	"\x03cpu\x18\x04 \x01(\v2\x04.CPUR\x03cpu\x12\x19\n" +
	"\x03ram\x18\x05 \x01(\v2\a.MemoryR\x03ram\x12%\n" +
	"\x04gpus\x18\x06 \x03(\v2\x04.GPUB\v\xbaH\b\xc8\x01\x01\x92\x01\x02\b\x01R\x04gpus\x121\n" +
	"\bstorages\x18\a \x03(\v2\b.StorageB\v\xbaH\b\xc8\x01\x01\x92\x01\x02\b\x01R\bstorages\x12\x1f\n" +
	"\x06screen\x18\b \x01(\v2\a.ScreenR\x06screen\x12%\n" +
	"\bkeyboard\x18\t \x01(\v2\t.KeyboardR\bkeyboard\x12\x1d\n" +
	"\tweight_kg\x18\n" +
	" \x01(\x01H\x00R\bweightKg\x12\x1f\n" +
	"\n" +
	"weight_lbs\x18\v \x01(\x01H\x00R\tweightLbs\x12.\n" +
	"\tprice_usd\x18\f \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\bpriceUsd\x12-\n" +
	"\frelease_year\x18\r \x01(\rB\n" +
	"\xbaH\a\xc8\x01\x01*\x02 \x00R\vreleaseYear\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06weightB\tZ\a/protocb\x06proto3"

var (
	file_laptop_laptop_message_proto_rawDescOnce sync.Once
	file_laptop_laptop_message_proto_rawDescData []byte
)

func file_laptop_laptop_message_proto_rawDescGZIP() []byte {
	file_laptop_laptop_message_proto_rawDescOnce.Do(func() {
		file_laptop_laptop_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptop_laptop_message_proto_rawDesc), len(file_laptop_laptop_message_proto_rawDesc)))
	})
	return file_laptop_laptop_message_proto_rawDescData
}

var file_laptop_laptop_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_laptop_laptop_message_proto_goTypes = []any{
	(*Laptop)(nil),                // 0: Laptop
	(*CPU)(nil),                   // 1: CPU
	(*Memory)(nil),                // 2: Memory
	(*GPU)(nil),                   // 3: GPU
	(*Storage)(nil),               // 4: Storage
	(*Screen)(nil),                // 5: Screen
	(*Keyboard)(nil),              // 6: Keyboard
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_laptop_laptop_message_proto_depIdxs = []int32{
	1, // 0: Laptop.cpu:type_name -> CPU
	2, // 1: Laptop.ram:type_name -> Memory
	3, // 2: Laptop.gpus:type_name -> GPU
	4, // 3: Laptop.storages:type_name -> Storage
	5, // 4: Laptop.screen:type_name -> Screen
	6, // 5: Laptop.keyboard:type_name -> Keyboard
	7, // 6: Laptop.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_laptop_laptop_message_proto_init() }
func file_laptop_laptop_message_proto_init() {
	if File_laptop_laptop_message_proto != nil {
		return
	}
	file_laptop_screen_message_proto_init()
	file_laptop_keyboard_message_proto_init()
	file_laptop_processor_message_proto_init()
	file_laptop_memory_message_proto_init()
	file_laptop_storage_message_proto_init()
	file_laptop_laptop_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Laptop_WeightKg)(nil),
		(*Laptop_WeightLbs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptop_laptop_message_proto_rawDesc), len(file_laptop_laptop_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laptop_laptop_message_proto_goTypes,
		DependencyIndexes: file_laptop_laptop_message_proto_depIdxs,
		MessageInfos:      file_laptop_laptop_message_proto_msgTypes,
	}.Build()
	File_laptop_laptop_message_proto = out.File
	file_laptop_laptop_message_proto_goTypes = nil
	file_laptop_laptop_message_proto_depIdxs = nil
}
