// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: laptop/laptop_service.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLaptopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Laptop        *Laptop                `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"` // Laptop to be created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLaptopRequest) Reset() {
	*x = CreateLaptopRequest{}
	mi := &file_laptop_laptop_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLaptopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaptopRequest) ProtoMessage() {}

func (x *CreateLaptopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaptopRequest.ProtoReflect.Descriptor instead.
func (*CreateLaptopRequest) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLaptopRequest) GetLaptop() *Laptop {
	if x != nil {
		return x.Laptop
	}
	return nil
}

type CreateLaptopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the created laptop
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLaptopResponse) Reset() {
	*x = CreateLaptopResponse{}
	mi := &file_laptop_laptop_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLaptopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaptopResponse) ProtoMessage() {}

func (x *CreateLaptopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaptopResponse.ProtoReflect.Descriptor instead.
func (*CreateLaptopResponse) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLaptopResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchLaptopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"` // Filter criteria for searching laptops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLaptopRequest) Reset() {
	*x = SearchLaptopRequest{}
	mi := &file_laptop_laptop_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLaptopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLaptopRequest) ProtoMessage() {}

func (x *SearchLaptopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLaptopRequest.ProtoReflect.Descriptor instead.
func (*SearchLaptopRequest) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchLaptopRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchLaptopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Laptop        *Laptop                `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"` // searched laptop response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLaptopResponse) Reset() {
	*x = SearchLaptopResponse{}
	mi := &file_laptop_laptop_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLaptopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLaptopResponse) ProtoMessage() {}

func (x *SearchLaptopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLaptopResponse.ProtoReflect.Descriptor instead.
func (*SearchLaptopResponse) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchLaptopResponse) GetLaptop() *Laptop {
	if x != nil {
		return x.Laptop
	}
	return nil
}

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadImageRequest_Info
	//	*UploadImageRequest_ChunkData
	Data          isUploadImageRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_laptop_laptop_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{4}
}

func (x *UploadImageRequest) GetData() isUploadImageRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetInfo() *ImageInfo {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadImageRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadImageRequest_Data interface {
	isUploadImageRequest_Data()
}

type UploadImageRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"` // Image information
}

type UploadImageRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"` // Image data chunk
}

func (*UploadImageRequest_Info) isUploadImageRequest_Data() {}

func (*UploadImageRequest_ChunkData) isUploadImageRequest_Data() {}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaptopId      string                 `protobuf:"bytes,1,opt,name=laptop_id,json=laptopId,proto3" json:"laptop_id,omitempty"`    // Unique identifier for the image
	ImageType     string                 `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"` // Type of the image (e.g., thumbnail, full-size)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_laptop_laptop_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{5}
}

func (x *ImageInfo) GetLaptopId() string {
	if x != nil {
		return x.LaptopId
	}
	return ""
}

func (x *ImageInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`      // Unique identifier for the uploaded image
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // Size of the uploaded image in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_laptop_laptop_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{6}
}

func (x *UploadImageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadImageResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RateLaptopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaptopId      string                 `protobuf:"bytes,1,opt,name=laptop_id,json=laptopId,proto3" json:"laptop_id,omitempty"` // Unique identifier for the laptop being rated
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                     // Rating score (e.g., 1-5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLaptopRequest) Reset() {
	*x = RateLaptopRequest{}
	mi := &file_laptop_laptop_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLaptopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLaptopRequest) ProtoMessage() {}

func (x *RateLaptopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLaptopRequest.ProtoReflect.Descriptor instead.
func (*RateLaptopRequest) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{7}
}

func (x *RateLaptopRequest) GetLaptopId() string {
	if x != nil {
		return x.LaptopId
	}
	return ""
}

func (x *RateLaptopRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RateLaptopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaptopId      string                 `protobuf:"bytes,1,opt,name=laptop_id,json=laptopId,proto3" json:"laptop_id,omitempty"`               // Unique identifier for the rated laptop
	RatedCount    uint32                 `protobuf:"varint,2,opt,name=rated_count,json=ratedCount,proto3" json:"rated_count,omitempty"`        // Total number of ratings received
	AverageScore  float64                `protobuf:"fixed64,3,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"` // Average score of the laptop
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLaptopResponse) Reset() {
	*x = RateLaptopResponse{}
	mi := &file_laptop_laptop_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLaptopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLaptopResponse) ProtoMessage() {}

func (x *RateLaptopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_laptop_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLaptopResponse.ProtoReflect.Descriptor instead.
func (*RateLaptopResponse) Descriptor() ([]byte, []int) {
	return file_laptop_laptop_service_proto_rawDescGZIP(), []int{8}
}

func (x *RateLaptopResponse) GetLaptopId() string {
	if x != nil {
		return x.LaptopId
	}
	return ""
}

func (x *RateLaptopResponse) GetRatedCount() uint32 {
	if x != nil {
		return x.RatedCount
	}
	return 0
}

func (x *RateLaptopResponse) GetAverageScore() float64 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

var File_laptop_laptop_service_proto protoreflect.FileDescriptor

const file_laptop_laptop_service_proto_rawDesc = "" +
	"\n" +
	"\x1blaptop/laptop_service.proto\x1a\x1blaptop/laptop_message.proto\x1a\x1blaptop/filter_message.proto\"6\n" +
	"\x13CreateLaptopRequest\x12\x1f\n" +
	"\x06laptop\x18\x01 \x01(\v2\a.LaptopR\x06laptop\"&\n" +
	"\x14CreateLaptopResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x13SearchLaptopRequest\x12\x1f\n" +
	"\x06filter\x18\x01 \x01(\v2\a.FilterR\x06filter\"7\n" +
	"\x14SearchLaptopResponse\x12\x1f\n" +
	"\x06laptop\x18\x01 \x01(\v2\a.LaptopR\x06laptop\"_\n" +
	"\x12UploadImageRequest\x12 \n" +
	"\x04info\x18\x01 \x01(\v2\n" +
	".ImageInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"G\n" +
	"\tImageInfo\x12\x1b\n" +
	"\tlaptop_id\x18\x01 \x01(\tR\blaptopId\x12\x1d\n" +
	"\n" +
	"image_type\x18\x02 \x01(\tR\timageType\"9\n" +
	"\x13UploadImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"F\n" +
	"\x11RateLaptopRequest\x12\x1b\n" +
	"\tlaptop_id\x18\x01 \x01(\tR\blaptopId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"w\n" +
	"\x12RateLaptopResponse\x12\x1b\n" +
	"\tlaptop_id\x18\x01 \x01(\tR\blaptopId\x12\x1f\n" +
	"\vrated_count\x18\x02 \x01(\rR\n" +
	"ratedCount\x12#\n" +
	"\raverage_score\x18\x03 \x01(\x01R\faverageScore2\x82\x02\n" +
	"\rLaptopService\x12;\n" +
	"\fCreateLaptop\x12\x14.CreateLaptopRequest\x1a\x15.CreateLaptopResponse\x12=\n" +
	"\fSearchLaptop\x12\x14.SearchLaptopRequest\x1a\x15.SearchLaptopResponse0\x01\x12:\n" +
	"\vUploadImage\x12\x13.UploadImageRequest\x1a\x14.UploadImageResponse(\x01\x129\n" +
	"\n" +
	"RateLaptop\x12\x12.RateLaptopRequest\x1a\x13.RateLaptopResponse(\x010\x01B\tZ\a/protocb\x06proto3"

var (
	file_laptop_laptop_service_proto_rawDescOnce sync.Once
	file_laptop_laptop_service_proto_rawDescData []byte
)

func file_laptop_laptop_service_proto_rawDescGZIP() []byte {
	file_laptop_laptop_service_proto_rawDescOnce.Do(func() {
		file_laptop_laptop_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptop_laptop_service_proto_rawDesc), len(file_laptop_laptop_service_proto_rawDesc)))
	})
	return file_laptop_laptop_service_proto_rawDescData
}

var file_laptop_laptop_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_laptop_laptop_service_proto_goTypes = []any{
	(*CreateLaptopRequest)(nil),  // 0: CreateLaptopRequest
	(*CreateLaptopResponse)(nil), // 1: CreateLaptopResponse
	(*SearchLaptopRequest)(nil),  // 2: SearchLaptopRequest
	(*SearchLaptopResponse)(nil), // 3: SearchLaptopResponse
	(*UploadImageRequest)(nil),   // 4: UploadImageRequest
	(*ImageInfo)(nil),            // 5: ImageInfo
	(*UploadImageResponse)(nil),  // 6: UploadImageResponse
	(*RateLaptopRequest)(nil),    // 7: RateLaptopRequest
	(*RateLaptopResponse)(nil),   // 8: RateLaptopResponse
	(*Laptop)(nil),               // 9: Laptop
	(*Filter)(nil),               // 10: Filter
}
var file_laptop_laptop_service_proto_depIdxs = []int32{
	9,  // 0: CreateLaptopRequest.laptop:type_name -> Laptop
	10, // 1: SearchLaptopRequest.filter:type_name -> Filter
	9,  // 2: SearchLaptopResponse.laptop:type_name -> Laptop
	5,  // 3: UploadImageRequest.info:type_name -> ImageInfo
	0,  // 4: LaptopService.CreateLaptop:input_type -> CreateLaptopRequest
	2,  // 5: LaptopService.SearchLaptop:input_type -> SearchLaptopRequest
	4,  // 6: LaptopService.UploadImage:input_type -> UploadImageRequest
	7,  // 7: LaptopService.RateLaptop:input_type -> RateLaptopRequest
	1,  // 8: LaptopService.CreateLaptop:output_type -> CreateLaptopResponse
	3,  // 9: LaptopService.SearchLaptop:output_type -> SearchLaptopResponse
	6,  // 10: LaptopService.UploadImage:output_type -> UploadImageResponse
	8,  // 11: LaptopService.RateLaptop:output_type -> RateLaptopResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_laptop_laptop_service_proto_init() }
func file_laptop_laptop_service_proto_init() {
	if File_laptop_laptop_service_proto != nil {
		return
	}
	file_laptop_laptop_message_proto_init()
	file_laptop_filter_message_proto_init()
	file_laptop_laptop_service_proto_msgTypes[4].OneofWrappers = []any{
		(*UploadImageRequest_Info)(nil),
		(*UploadImageRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptop_laptop_service_proto_rawDesc), len(file_laptop_laptop_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_laptop_laptop_service_proto_goTypes,
		DependencyIndexes: file_laptop_laptop_service_proto_depIdxs,
		MessageInfos:      file_laptop_laptop_service_proto_msgTypes,
	}.Build()
	File_laptop_laptop_service_proto = out.File
	file_laptop_laptop_service_proto_goTypes = nil
	file_laptop_laptop_service_proto_depIdxs = nil
}
