// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: laptop/processor_message.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NumCores      uint32                 `protobuf:"varint,3,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	NumThreads    uint32                 `protobuf:"varint,4,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	MinGhz        float64                `protobuf:"fixed64,5,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz        float64                `protobuf:"fixed64,6,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_laptop_processor_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_processor_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_laptop_processor_message_proto_rawDescGZIP(), []int{0}
}

func (x *CPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CPU) GetNumCores() uint32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *CPU) GetNumThreads() uint32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

func (x *CPU) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *CPU) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

type GPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinGhz        float64                `protobuf:"fixed64,3,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz        float64                `protobuf:"fixed64,4,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	Memory        *Memory                `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPU) Reset() {
	*x = GPU{}
	mi := &file_laptop_processor_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_processor_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_laptop_processor_message_proto_rawDescGZIP(), []int{1}
}

func (x *GPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPU) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *GPU) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

func (x *GPU) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_laptop_processor_message_proto protoreflect.FileDescriptor

const file_laptop_processor_message_proto_rawDesc = "" +
	"\n" +
	"\x1elaptop/processor_message.proto\x1a\x1blaptop/memory_message.proto\"\x9f\x01\n" +
	"\x03CPU\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tnum_cores\x18\x03 \x01(\rR\bnumCores\x12\x1f\n" +
	"\vnum_threads\x18\x04 \x01(\rR\n" +
	"numThreads\x12\x17\n" +
	"\amin_ghz\x18\x05 \x01(\x01R\x06minGhz\x12\x17\n" +
	"\amax_ghz\x18\x06 \x01(\x01R\x06maxGhz\"\x82\x01\n" +
	"\x03GPU\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\amin_ghz\x18\x03 \x01(\x01R\x06minGhz\x12\x17\n" +
	"\amax_ghz\x18\x04 \x01(\x01R\x06maxGhz\x12\x1f\n" +
	"\x06memory\x18\x05 \x01(\v2\a.MemoryR\x06memoryB\tZ\a/protocb\x06proto3"

var (
	file_laptop_processor_message_proto_rawDescOnce sync.Once
	file_laptop_processor_message_proto_rawDescData []byte
)

func file_laptop_processor_message_proto_rawDescGZIP() []byte {
	file_laptop_processor_message_proto_rawDescOnce.Do(func() {
		file_laptop_processor_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptop_processor_message_proto_rawDesc), len(file_laptop_processor_message_proto_rawDesc)))
	})
	return file_laptop_processor_message_proto_rawDescData
}

var file_laptop_processor_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_laptop_processor_message_proto_goTypes = []any{
	(*CPU)(nil),    // 0: CPU
	(*GPU)(nil),    // 1: GPU
	(*Memory)(nil), // 2: Memory
}
var file_laptop_processor_message_proto_depIdxs = []int32{
	2, // 0: GPU.memory:type_name -> Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_laptop_processor_message_proto_init() }
func file_laptop_processor_message_proto_init() {
	if File_laptop_processor_message_proto != nil {
		return
	}
	file_laptop_memory_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptop_processor_message_proto_rawDesc), len(file_laptop_processor_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laptop_processor_message_proto_goTypes,
		DependencyIndexes: file_laptop_processor_message_proto_depIdxs,
		MessageInfos:      file_laptop_processor_message_proto_msgTypes,
	}.Build()
	File_laptop_processor_message_proto = out.File
	file_laptop_processor_message_proto_goTypes = nil
	file_laptop_processor_message_proto_depIdxs = nil
}
